---
name: Checks

on: [push]

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-20.04
    steps:
      - name: change directory
        run: cd app/
      - name: Unit Testing
        run: python manage.py test