---
name: Checks

on: [push]

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-20.04
    steps:
      # Checkout the GitHub repo
      - uses: actions/checkout@v2

      # Install Python 3.10
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      # Pip install project dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Move into the Django project folder (./app) and run pytest
      - name: Test
        working-directory: ./app
        run: python manage.py test